theme = "onedark"

[editor]
mouse = false
true-color = true
color-modes = true
undercurl = true
bufferline = "multiple"
line-number = "relative"
cursorline = true
auto-format = true
auto-save = true
popup-border = "all"
shell = ["zsh", "-c"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "version-control"]
center = ["file-base-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "spinner", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
auto-signature-help = false
# display-inlay-hints = true

[editor.indent-guides]
render = true
# skip-levels = 1

# Keybinds
[keys.normal]
g = { a = "code_action" } # map 'ga' to show code actions
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["open_below", "normal_mode"]
S-ret = ["open_below", "normal_mode", "move_visual_line_up"]
"tab" = ":bn" 
"S-tab" = ":bp"
X = "extend_line_above"
K = "hover"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

[keys.insert]
C-p = "signature_help"
