theme = "ayu_shift"

[editor]
mouse = true
true-color = true
color-modes = true
undercurl = true
bufferline = "multiple"
line-number = "relative"
cursorline = true
auto-format = true
auto-save = true
popup-border = "all"
shell = ["zsh", "-c"]
# end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode","spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["workspace-diagnostics","position-percentage", "position", "file-encoding"]

[editor.lsp]
display-messages = true
auto-signature-help = false
# display-inlay-hints = true

[editor.indent-guides]
render = true
# skip-levels = 1

# [editor.inline-diagnostics]
# cursor-line = "warning"

# Keybinds
[keys.normal]
g = { a = "code_action" } # map 'ga' to show code actions
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["open_below", "normal_mode"]
S-ret = ["open_below", "normal_mode", "move_visual_line_up"]
"tab" = ":bn" 
"S-tab" = ":bp"
X = "extend_line_above"
K = "hover"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]
# open lazygit in popup pane
C-g = ":sh tmux send-keys -t 2 lazygit Enter && tmux select-pane -t 2"
C-S-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"

[keys.insert]
C-p = "signature_help"
